/**
 * CONTRACT: scripts/lib/manifest-card.mjs
 * ROLE: renders a dump manifest as a markdown card and finds changed dump slugs
 * EXPORTS:
 *   CARD_MARKER — the sticky-comment marker every rendered card starts with
 *   dumpSlugsFromFiles — content/dumps/<slug>/... paths → unique sorted slugs
 *   renderManifestCard — manifest + slug (+ the summary.md brief) → a sticky PR-comment body
 * INVARIANTS:
 *   — the manifest is the only source; the card renders it and never invents fields
 *   — the summary hook and the folded summary.md brief are omitted when absent
 */

// The PR-comment poster looks for this marker to update the existing comment
// instead of stacking a new one on every push.
export const CARD_MARKER = '<!-- dump-manifest -->';

// Field order and human labels for the card. Labels are PR-reviewer facing, so
// they are spelled out rather than the raw manifest keys.
const FIELDS = [
  ['title', 'Title'],
  ['type', 'Type'],
  ['domain', 'Domain'],
  ['stakes', 'Stakes'],
  ['content_flags', 'Content flags'],
  ['trust_level', 'Trust level'],
  ['generated_by', 'Generated by'],
  ['human_review', 'Human review'],
  ['verification', 'Verification'],
  ['license', 'Licence'],
  ['sources', 'Sources'],
  ['tags', 'Tags'],
];

// Author text is untrusted: escape angle brackets so a string cannot inject
// raw HTML into the comment. `&` is left alone so existing entities are not double-escaped.
const escapeAngles = (value) => String(value).replace(/</g, '&lt;').replace(/>/g, '&gt;');

const cell = (value) =>
  escapeAngles(String(value).replace(/\|/g, '\\|').replace(/\s*\n+\s*/g, ' ')).trim();
const asCell = (value) => (Array.isArray(value) ? value.map(cell).join(', ') : cell(value));

// dumpSlugsFromFiles(files) → every slug under content/dumps/<slug>/ in the list
export function dumpSlugsFromFiles(files) {
  const slugs = new Set();
  for (const file of files) {
    const match = /^content\/dumps\/([^/]+)\//.exec(String(file).trim());
    if (match) slugs.add(match[1]);
  }
  return [...slugs].sort();
}

// renderManifestCard(manifest, slug, summaryBrief?) → the sticky PR-comment body.
// summaryBrief is the text of content/dumps/<slug>/summary.md when that file exists.
export function renderManifestCard(manifest, slug, summaryBrief = '') {
  const rows = [];
  for (const [key, label] of FIELDS) {
    const value = manifest[key];
    if (value === undefined || value === null || value === '') continue;
    if (Array.isArray(value) && value.length === 0) continue;
    rows.push(`| ${label} | ${asCell(value)} |`);
  }

  const parts = [CARD_MARKER, `### Dump manifest — \`${slug}\``, ''];
  // The hook always shows; the full human brief folds away for a one-click read.
  if (manifest.summary) parts.push(`**What it is:** ${cell(manifest.summary)}`, '');
  const brief = escapeAngles(String(summaryBrief || '').trim());
  if (brief) parts.push('<details><summary>Human brief (summary.md)</summary>', '', brief, '', '</details>', '');
  parts.push('| Field | Value |', '| --- | --- |', ...rows, '');
  parts.push(
    brief
      ? `> Auto-generated from \`content/dumps/${slug}/manifest.json\` and \`summary.md\` — edit the files, not this comment.`
      : `> Auto-generated from \`content/dumps/${slug}/manifest.json\` — edit the manifest, not this comment.`,
    '',
  );
  return parts.join('\n');
}
