#!/usr/bin/env node
/**
 * CONTRACT: scripts/contract.mjs
 * ROLE: contract-header validator + module-index generator for AGENTS/code-map.md
 * EXPORTS:
 *   MARK_BEGIN — the opening marker of the generated module index
 *   MARK_END — the closing marker of the generated module index
 *   actualExports — the module's real ES export names
 *   actualImports — the module's real import specifiers
 *   contractFiles — every first-party module path, sorted
 *   generateIndex — the AGENTS/code-map.md module-index text
 *   parseHeader — reads a module's CONTRACT header
 *   rewriteIndex — regenerates that section in place (true on change)
 *   validate — compares a header with the module's real exports/imports
 *   validateAll — header problems across every module
 * CONSUMES:
 *   node:fs — read modules, rewrite the map
 *   node:path — resolve the trees and the map
 *   node:url — find the repo root and detect the entry point
 * INVARIANTS:
 *   — the map cannot lie: a header must equal the code's exports/imports both ways
 *   — scripts is read non-recursively so scripts/lib is never indexed twice
 */
// Contract-header validator + module-index generator (AGENTS/code-map.md).
//
// Every first-party module opens with a contract header — the first block comment:
//
//   /**
//    * CONTRACT: scripts/lib/machine.mjs
//    * ROLE: one-line: what this module is for
//    * EXPORTS:
//    *   writeMachineFiles — writes index.json, well-known, feeds, tags
//    *   writeSitemap — writes sitemap.xml
//    * CONSUMES:
//    *   node:fs/promises — the filesystem
//    *   ./dumps.mjs — the §5.1 index entries
//    * INVARIANTS:
//    *   — one truth per machine file: the controller writes them, the engine never does
//    */
//
// The header is parsed and checked against the module's ACTUAL export and import
// statements (set equality both ways), so the map cannot lie. The module index
// between the MODULE-INDEX markers in AGENTS/code-map.md is generated from the
// headers. Drift exits 1.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ARCH = path.join(ROOT, 'AGENTS', 'code-map.md');

// The first-party module trees. `scripts` is read non-recursively because it
// contains `scripts/lib` (walked as its own tree) — no module is indexed twice.
const TREES = [
  { dir: 'scripts/lib', recursive: true },
  { dir: 'scripts', recursive: false },
  { dir: 'input/controllers', recursive: false },
];

export const MARK_BEGIN = '<!-- MODULE-INDEX:START (generated by npm run contract — do not edit) -->';
export const MARK_END = '<!-- MODULE-INDEX:END -->';

// parseHeader(src) → { contract, role, exports[], consumes[], invariants[] } | null
export function parseHeader(src) {
  // BOM-proof and shebang-proof: a \uFEFF or a leading #! line would make the
  // anchor fail and the whole header read as garbage.
  const m = src.replace(/^\uFEFF/, '').replace(/^#![^\n]*\r?\n/, '').match(/^\/\*\*([\s\S]*?)\*\//);
  if (!m) return null;
  const h = { contract: '', role: '', exports: [], consumes: [], invariants: [] };
  let section = null;
  // CRLF-proof: '.' never matches \r, so a trailing \r would break every key regex.
  for (const raw of m[1].split(/\r?\n/)) {
    const key = raw.match(/^\s*\*\s+(CONTRACT|ROLE|EXPORTS|CONSUMES|INVARIANTS):(.*)$/);
    if (key) {
      section = key[1].toLowerCase();
      const inline = key[2].trim();
      if (section === 'contract' && inline) h.contract = inline;
      if (section === 'role' && inline) h.role = inline;
      continue;
    }
    const text = raw.replace(/^\s*\*\s?/, '').trim();
    if (!text || !section) continue;
    if (section === 'exports' || section === 'consumes') {
      const e = text.match(/^([\w$.:/@-]+)\s+—\s+(.*)$/);
      if (e) h[section].push({ name: e[1], note: e[2].trim() });
    } else if (section === 'invariants') {
      h.invariants.push(text.replace(/^—\s*/, '').trim());
    }
  }
  return h;
}

// actualExports(src) → sorted names of the module's ES exports
export function actualExports(src) {
  const out = new Set();
  const re = /export\s+(?:async\s+)?(?:function\s*\*?|class|const)\s+([A-Za-z_$][\w$]*)/g;
  let m;
  while ((m = re.exec(src))) out.add(m[1]);
  const reList = /export\s*\{([^}]*)\}/g;
  while ((m = reList.exec(src))) {
    for (const part of m[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/).pop().trim();
      if (name) out.add(name);
    }
  }
  return [...out].sort();
}

// actualImports(src) → sorted module specifiers the module imports
export function actualImports(src) {
  const out = new Set();
  const re = /import\s+(?:[\s\S]*?from\s+)?['"]([^'"]+)['"]/g;
  let m;
  while ((m = re.exec(src))) out.add(m[1]);
  return [...out].sort();
}

// validate(name, src) → problems[] (empty = the header matches the module)
export function validate(name, src) {
  const problems = [];
  const h = parseHeader(src);
  if (!h) return ['no contract header (must open with a /** CONTRACT: ... */ block)'];
  if (h.contract !== name) problems.push(`CONTRACT says "${h.contract || '—'}", expected "${name}"`);
  if (!h.role) problems.push('ROLE is empty');
  const declared = h.exports.map((e) => e.name);
  const real = actualExports(src);
  const missing = real.filter((n) => !declared.includes(n));
  const extra = declared.filter((n) => !real.includes(n));
  if (missing.length) problems.push(`exports missing from header: ${missing.join(', ')}`);
  if (extra.length) problems.push(`exports in header, not in code: ${extra.join(', ')}`);
  for (const e of h.exports) if (!e.note) problems.push(`export ${e.name} has no one-liner note`);
  const declaredIn = h.consumes.map((e) => e.name);
  const realIn = actualImports(src);
  const inMissing = realIn.filter((n) => !declaredIn.includes(n));
  const inExtra = declaredIn.filter((n) => !realIn.includes(n));
  if (inMissing.length) problems.push(`imports missing from CONSUMES: ${inMissing.join(', ')}`);
  if (inExtra.length) problems.push(`CONSUMES entries never imported: ${inExtra.join(', ')}`);
  return problems;
}

// contractFiles() → sorted repo-relative posix paths of every first-party module
export function contractFiles() {
  const out = [];
  const walk = (dir, rel, recursive) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const r = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) {
        if (recursive) walk(path.join(dir, e.name), r, recursive);
        continue;
      }
      if (/\.(mjs|js)$/.test(e.name)) out.push(r);
    }
  };
  for (const t of TREES) walk(path.join(ROOT, t.dir), t.dir.split(path.sep).join('/'), t.recursive);
  return [...new Set(out)].sort();
}

// generateIndex() → the AGENTS/code-map.md section text between the markers
export function generateIndex() {
  const lines = [MARK_BEGIN, ''];
  for (const name of contractFiles()) {
    const src = fs.readFileSync(path.join(ROOT, name), 'utf8');
    const h = parseHeader(src);
    lines.push(`- **${name}** — ${h ? h.role || '—' : 'NO CONTRACT HEADER'}`);
    if (h) {
      if (h.exports.length) lines.push(`  exports: ${h.exports.map((e) => e.name).join(', ')}`);
      if (h.consumes.length) lines.push(`  consumes: ${h.consumes.map((e) => e.name).join(', ')}`);
      if (h.invariants.length) lines.push(`  invariants: ${h.invariants.map((i) => `— ${i}`).join('; ')}`);
    }
  }
  lines.push('', MARK_END);
  return lines.join('\n');
}

// rewriteIndex() → true if the AGENTS/code-map.md index section changed
export function rewriteIndex() {
  if (!fs.existsSync(ARCH)) return false;
  const doc = fs.readFileSync(ARCH, 'utf8');
  const b = doc.indexOf(MARK_BEGIN);
  const e = doc.indexOf(MARK_END);
  let next;
  if (b === -1 || e === -1) {
    next = doc.replace(/\s*$/, '\n\n### Module map\n\n' + generateIndex() + '\n');
  } else {
    next = doc.slice(0, b) + generateIndex() + doc.slice(e + MARK_END.length);
  }
  if (next !== doc) {
    fs.writeFileSync(ARCH, next);
    return true;
  }
  return false;
}

// validateAll() → problems[] across every first-party module (empty = clean)
export function validateAll() {
  const problems = [];
  for (const name of contractFiles()) {
    const src = fs.readFileSync(path.join(ROOT, name), 'utf8');
    for (const p of validate(name, src)) problems.push(`${name}: ${p}`);
  }
  return problems;
}

function dump() {
  for (const name of contractFiles()) {
    const src = fs.readFileSync(path.join(ROOT, name), 'utf8');
    console.log(`== ${name}`);
    console.log(`   exports: ${actualExports(src).join(', ') || '(none)'}`);
    console.log(`   imports: ${actualImports(src).join(', ') || '(none)'}`);
  }
}

const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMain) {
  if (process.argv.includes('--dump')) {
    dump();
  } else {
    const problems = validateAll();
    const changed = rewriteIndex();
    if (changed) console.log('AGENTS/code-map.md module index regenerated');
    if (problems.length) {
      console.error(problems.map((p) => `DRIFT ${p}`).join('\n'));
      process.exit(1);
    }
    console.log(`contract OK: ${contractFiles().length} modules, headers match code`);
  }
}
